spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://api.bonelf.com:3306/bonelf-user?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: bonelf
          password: 567215
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: api.bonelf.com
    port: 6379
    password: 567215

  cloud:
    nacos:
      discovery:
        server-addr: nacos.bonelf.com:80
    stream:
      rocketmq:
        binder:
          name-server: api.bonelf.com:9876
          # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
          bindings:
            input:
              consumer:
                # 同步消费消息模式
                orderly: true
                tags: SocketTag||DictTag||TestTag||websocket-user # tag 为 tag1/tag2/tag3/tag4
            output:
              producer:
                group: user
      bindings:
        # consumer
        input: { destination: websocketTopic, group: support, content-type: text/plain, consumer.maxAttempts: 1 }
        # provider
        output: { destination: BNF_user, content-type: application/json }