spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://api.bonelf.com:3306/bonelf-test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: bonelf
          password: 567215
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: api.bonelf.com
    port: 6379
    password: 567215

  cloud:
    nacos:
      discovery:
        server-addr: nacos.bonelf.com:80
#        server-addr: api.bonelf.com:8848
    stream:
      rocketmq:
        binder:
          # RocketMQ Namesrv 地址
          name-server: api.bonelf.com:9876
          bindings:
            input:
              consumer:
                enable: false
                # 同步消费消息模式
                orderly: true
                tags: SocketTag||DictTag # tag 为 tag1/tag2/tag3/tag4
            output:
              producer:
                enable: false
      bindings:
        input:
          destination: websocketTopic
          content-type: text/plain
          group: ${spring.application.name}
          consumer.maxAttempts: 1
        output:
          destination: BNF_${spring.application.name}
          content-type: application/json

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
  # 服务注册到 nacos
  registry:
    type: nacos
    nacos:
      # 想配置group和application但是包里没读取？
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: ""
      group: DEFAULT_GROUP
      username: "nacos"
      password: "nacos"
      cluster: default
  config:
    type: nacos
    nacos:
      serverAddr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: ""
      username: "nacos"
      password: "nacos"
      group: SEATA_GROUP