server:
  port: 8800

spring:
  profiles:
    active: test
    include:
      - common

  http:
    encoding:
      # 解决静态文本文件编码错误
      force: true

bonelf:
  upload:
    type: ftp
  oauth2:
    # new AntPathRequestMatcher(pattern, method)
    permit-path: /vCode/**,/resource/**,/image/**
  qrcode:
    ticket-uri:
      temp: N/A
    # 有效期限制的url
    limit-ticket-uri:
      9b8c1028acf: user:shop/page?lat=30.00&lng=120.001
    permit-urls: user:shop/page
  # websocket配置
  websocket:
    type: stomp
    topic-type: mq
    # WebsocketProperties
    # 在不使用Mq、stomp主动获取的情况（见 link? ）下，由support主动将消息通过 feign或者redis发布订阅 发给服务 需要配置cmdMap 来处理指令消息和处理的服务对应关系，各服务需提供接收消息接口（frame-websocket已实现）。
    # 使用 Mq 通过订阅websocketTopic主题下的tag(@StreamListener)来实现主动接收，
    # 使用 stomp 则通过 @MessageMapping 来实现主动接收，推荐使用stomp结合Mq的方式