spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://api.bonelf.com:3306/bonelf-support?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: bonelf
          password: 567215
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: api.bonelf.com
    port: 6379
    password: 567215

  cloud:
    nacos:
      discovery:
        server-addr: nacos.bonelf.com:80
    stream:
      rocketmq:
        binder:
          name-server: api.bonelf.com:9876
          # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
          bindings:
            output:
              producer:
                group: user
      bindings:
        # provider
        output: { destination: BNF_support, content-type: application/json }

bonelf:
  rocketmq:
    enable: false
  websocket:
    type: stomp