spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/bonelf-demo?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: bonelf
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: 127.0.0.1:9876
          bindings:
            input:
              consumer:
                enable: false
                # 同步消费消息模式
                orderly: true
                tags: SocketTag||DictTag # tag 为 tag1/tag2/tag3/tag4
            output:
              producer:
                enable: false
      bindings:
        input:
          destination: BNF_support
          content-type: text/plain
          group: ${spring.application.name}
          consumer.maxAttempts: 1
        output:
          destination: BNF_${spring.application.name}
          content-type: application/json

rocketmq:
  enable: false