spring:
  cloud:
    nacos:
      discovery:
        # server-addr: 192.168.31.60:8848
        server-addr: 192.168.31.60:8848
    stream:
      rocketmq:
        binder:
          name-server: 192.168.31.60:9876
#  datasource:
#    dynamic:
#      primary: master
#      datasource:
#        master:
#          url: jdbc:mysql://192.168.31.60:3306/bonelf-gateway?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#          username: bonelf
#          password: 567215
#          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.31.60
    port: 6379
    password: '567215'